### ISSUE TITLE
Catalina 10.15.4 has broken twofa

### ISSUE THREAD

**Issue by jodrell2000** [sqreen/twofa#4]
My MBP upgraded itself last night and now twofa won't start. It just dies immediately

```
$ twofa
[1]    15344 killed     twofa
```

Below is the output from Console for twofa suggesting that this is a signature issue
```
default	16:15:40.116776+0100	kernel	mac_vnode_check_signature: /usr/local/Cellar/twofa/0.0.1/bin/TwoFa: code signature validation failed fatally: When validating /usr/local/Cellar/twofa/0.0.1/bin/TwoFa:
  The signature could not be validated because AMFI could not load its entitlements for validation: entitlements cannot be parsed
default	16:15:40.116828+0100	kernel	proc 15082: load code signature error 4 for file "TwoFa"
default	16:15:40.117675+0100	kernel	Security policy would not allow process: 15082, /usr/local/Cellar/twofa/0.0.1/bin/TwoFa
default	16:15:40.161308+0100	ReportCrash	Parsing corpse data for process TwoFa [pid 15082]
default	16:15:40.882122+0100	ReportCrash	Saved crash report for TwoFa[15082] version ??? to TwoFa_2020-04-02-161540_user.crash
default	16:15:40.931941+0100	ReportCrash	Removing excessive log: TwoFa_2020-04-02-104337_user.crash
```

**Comment by tewe** [comment]
Same on High Sierra after Security Update 2020-002.

```
default	15:16:36.881229 +0200	kernel	Failed to parse entitlements: AMFIUnserializeXML: duplicate dictionary key near line 10
default	15:16:36.881247 +0200	kernel	mac_vnode_check_signature: /usr/local/Cellar/twofa/0.0.1/bin/TwoFa: code signature validation failed fatally: When validating /usr/local/Cellar/twofa/0.0.1/bin/TwoFa:
  The signature could not be validated because AMFI could not load its entitlements for validation: entitlements cannot be parsed
```

So it can probably be fixed by removing the duplicate `com.apple.application-identifier` in https://github.com/sqreen/twofa/blob/master/Supporting/twofa.entitlements

**Comment by whoisbenli** [comment]
I am having this issue as well. I installed from homebrew on catalina.

**Comment by tedpearson** [comment]
@kirsis - any chance of getting you to spend any time releasing a bugfix to make TwoFa work with the latest security updates and with catalina? I'd love to keep using this but I don't particularly want to figure out the signing procedure, going to have to abandon it for 1password CLI tools otherwise.

**Comment by jkirsteins** [comment]
Hi all,

Sorry it’s not working. I’ve been meaning to get around to taking a look but never got around to it yet.

I’ll take a look this weekend and post an update.

**Comment by kirsis** [comment]
I started looking into this in a 'catalina' branch.

It looks like I need to notarize the tool before it will run. I started working on it but got stuck due to an issue with my developer account. 

I reached out to Apple, resolution pending their response.

**Comment by jkirsteins** [comment]
I've uploaded a new release, which runs on Catalina. Note that:

- it is not distributed via homebrew (I need to remember how to package files for homebrew);
- it appears that macOS **is not allowing access to the previously added keychain items**. I'm guessing it's due to the changes in entitlements. However, without these changes, the app would not run at all. I'm not sure there's a solution here, and if anybody has some insight, please let me know;
- since the application is not notarized, Gatekeeper will refuse running it by default. You will need to go to System Preferences -> Security & Privacy, and allow the tool to run;
- it's compiled with Swift 5 now, which means it will only run on macOS 10.15 (older versions do not have the Swift 5 runtime included).

The last point can be fixed by notarizing the tool, so I need to look into that. 

But the core issue - running on Catalina - is resolved.
